In [1]:
#尽可能多地使用 A 的列来构造一个矩阵 B，使得方程 Bx=0 只有平凡解,即x需要令B的列线性无关
import numpy as np

In [2]:
#对输入矩阵进行行化简，返回（列表，矩阵），pivot_cols指矩阵哪几列线性无关，M是返回变换后的RREF矩阵
def find_pivot_columns(mat):          #定义新函数
    M = mat.copy()                    #复制一个样本
    rows,cols = M.shape               #得到矩阵形状（行数，列数）
    pivot_cols = []                   #设一个空列表装主元列的编号
    row = 0                           #初始化行指针

    for col in range(cols):           #从左到右扫描每一列，range(cols)会生成一个从0到cols-1的整数序列，用于遍历所有列索引。
        if row >= rows:               #防止行指针溢出
            break
        pivot_row = row               #记录当前列中绝对值最大的那一行的索引
        max_val = abs(M[row,col])     #记录当前找到的最大绝对值，abs()求绝对值
        for r in range(row + 1,rows): #遍历每一行，得到本列的主元行
            if abs(M[r, col]) > max_val:
                max_val = abs(M[r, col])
                pivot_row = r
        
        if max_val < 1e-12:
            continue              #如果该列都为0，则一定不是主元列，遍历到下一列
        
        if pivot_row != row:      #交换主元行
            M[[row, pivot_row]] = M[[pivot_row, row]] #numpy特有的花式索引，二行互换。
            
        pivot = M[row, col]           #归一
        M[row, :] = M[row, :] / pivot # ：表示所有列，意思是选中第row行的整行数据

        for r in range(rows):         #消去其他所有行的这一列
            if r != row and abs(M[r, col]) > 1e-12:  #同时满足非主元行且值不为0时
                factor = M[r, col]
                M[r, :] = M[r, :] - factor * M[row, :]  #整行加减

        pivot_cols.append(col)    #记录这一列是主元列
        row += 1                  # 移到下一行

    return pivot_cols, M

In [3]:
A47 = np.array([
    [8, -3, 0, -7, 2],
    [-9, 4, 5, 11, -7],
    [6, -2, 2, -4, 4],
    [5, -1, 7, 0, 10]
], dtype=float)          #转换为浮点数形式

A48 = np.array([
    [12, 10, -6, -3, 7, 10],
    [-7, -6, 4, 7, -9, 5],
    [9, 9, -9, -5, 5, -1],
    [-4, -3, 1, 6, -8, 9],
    [8, 7, -5, -9, 11, -8]
], dtype=float)

In [4]:
pivots_47, RREF_47 = find_pivot_columns(A47)
print("主元列（0开始）:", pivots_47)
B47 = A47[:, pivots_47]   #从A47中取出所有行，但只取主元列对应的那几列
print("矩阵 B:\n", B47)

print("秩:", np.linalg.matrix_rank(B47)) #计算秩numpy内置函数

主元列（0开始）: [0, 1, 4]
矩阵 B:
 [[ 8. -3.  2.]
 [-9.  4. -7.]
 [ 6. -2.  4.]
 [ 5. -1. 10.]]
秩: 3


In [5]:
pivots_48, RREF_48 = find_pivot_columns(A48)
print("主元列（0开始）:", pivots_48)
B48 = A48[:, pivots_48]   #从A48中取出所有行，但只取主元列对应的那几列
print("矩阵 B:\n", B48)

print("秩:", np.linalg.matrix_rank(B48)) #计算秩numpy内置函数

主元列（0开始）: [0, 1, 3, 5]
矩阵 B:
 [[12. 10. -3. 10.]
 [-7. -6.  7.  5.]
 [ 9.  9. -5. -1.]
 [-4. -3.  6.  9.]
 [ 8.  7. -9. -8.]]
秩: 4
