In [6]:
#选取 A的一个未用于构建 B 的列向量 v ，并判断 v 是否属于由 B 的列向量所张成的集合。
import numpy as np

In [7]:
A = np.array([
    [12, 10, -6, -3, 7, 10],
    [-7, -6, 4, 7, -9, 5],
    [9, 9, -9, -5, 5, -1],
    [-4, -3, 1, 6, -8, 9],
    [8, 7, -5, -9, 11, -8]
], dtype=float)

pivot_indices = [0, 1, 3, 5]
B = A[:, pivot_indices]

print("矩阵 A:")
print(A)
print("\n矩阵 B (由 A 的主元列组成):")
print(B)

矩阵 A:
[[12. 10. -6. -3.  7. 10.]
 [-7. -6.  4.  7. -9.  5.]
 [ 9.  9. -9. -5.  5. -1.]
 [-4. -3.  1.  6. -8.  9.]
 [ 8.  7. -5. -9. 11. -8.]]

矩阵 B (由 A 的主元列组成):
[[12. 10. -3. 10.]
 [-7. -6.  7.  5.]
 [ 9.  9. -5. -1.]
 [-4. -3.  6.  9.]
 [ 8.  7. -9. -8.]]


In [8]:
all_indices = set(range(A.shape[1]))    #A47.shape[1]指获得A的列数，range(5)指会生成一个0到4的数字序列，
used_indices = set(pivot_indices)       #set(...)是把这个序列变成集合，集合是没有编号的
unused_indices = list(all_indices - used_indices)    #set间可以直接做减法，list(...)把集合转为列表，产生编号

v_col_index = unused_indices[0]    #选择第2列为v
v = A[:, v_col_index]

print(f"\n选择的未使用列索引: {v_col_index}")
print(f"向量 v (A 的第 {v_col_index} 列):")
print(v)


选择的未使用列索引: 2
向量 v (A 的第 2 列):
[-6.  4. -9.  1. -5.]


In [9]:
try:
    # 求解 Bx = v
    x, residuals, rank, s = np.linalg.lstsq(B, v, rcond=None)  #NUMPY中求解线性最小二乘问题的函数
    #x为最优解向量（精确解或近似解），residuals是残差平方和∣Bx-v∣^2,rank是B矩阵的秩，s为B的奇异值数组
    
    print(f"\n计算结果:")
    print(f"方程 Bx = v 的解 x: {x}")
    
    # 验证 Bx 是否等于 v
    reconstructed_v = B @ x    #@为矩阵乘法符号
    
    # 检查误差
    error = np.linalg.norm(reconstructed_v - v)   #计算向量的欧几里得范数，∣Bx-v∣，若此值极小，则Bx=v成立
    
    print(f"验证误差 (||Bx - v||): {error:.10f}")
    
    if error < 1e-9:
        print(f"\n结论: 向量 v 在矩阵 B 的列空间中")
        print("原因: 方程 Bx = v 存在精确解。")
    else:
        print(f"\n结论: 向量 v 不在矩阵 B 的列空间中。")

except np.linalg.LinAlgError:
    print("计算过程中发生错误。")



计算结果:
方程 Bx = v 的解 x: [ 2.00000000e+00 -3.00000000e+00 -1.35843972e-16 -1.84691620e-16]
验证误差 (||Bx - v||): 0.0000000000

结论: 向量 v 在矩阵 B 的列空间中
原因: 方程 Bx = v 存在精确解。


In [10]:
print('''
发现规律：从A中任意选一个非主元列，都一定在B的列向量张成的空间里。
也就是说，在任何一个矩阵中，主元列构成了列空间的一组基。非主元列不会给列空间增加任何新的维度，且都可以被主元列线性表示。
由于行化简不会改变矩阵各列之间的线性关系，所以行化简可以揭示这个规律。
''')


发现规律：从A中任意选一个非主元列，都一定在B的列向量张成的空间里。
也就是说，在任何一个矩阵中，主元列构成了列空间的一组基。非主元列不会给列空间增加任何新的维度，且都可以被主元列线性表示。
由于行化简不会改变矩阵各列之间的线性关系，所以行化简可以揭示这个规律。

