In [1]:
#判定所给矩阵是否单射：进行行化简，后观察列主元个数是否等于列数，即是否列满秩。
import numpy as np

In [2]:
A45 = np.array([
    [-5, 10, -5,  4],
    [ 8,  3, -4,  7],
    [ 4, -9,  5, -3],
    [-3, -2,  5,  4]
], dtype=float)

A46 = np.array([
     [ 7,  5,  4, -9],
    [10,  6, 16, -4],
    [12,  8, 12,  7],
    [-8, -6, -2,  5]
], dtype=float)

In [3]:
#计算矩阵的秩和列数
rank45 = np.linalg.matrix_rank(A45)   
n_cols45 = A45.shape[1] 

rank46 = np.linalg.matrix_rank(A46)   
n_cols46 = A46.shape[1] 

In [4]:
print("矩阵 A45：")
print(A45)
print(f"\n矩阵的秩（Rank）：{rank45}")
print(f"矩阵的列数：{n_cols45}")

print("\n矩阵 A46：")
print(A46)
print(f"\n矩阵的秩（Rank）：{rank46}")
print(f"矩阵的列数：{n_cols46}")

矩阵 A45：
[[-5. 10. -5.  4.]
 [ 8.  3. -4.  7.]
 [ 4. -9.  5. -3.]
 [-3. -2.  5.  4.]]

矩阵的秩（Rank）：3
矩阵的列数：4

矩阵 A46：
[[ 7.  5.  4. -9.]
 [10.  6. 16. -4.]
 [12.  8. 12.  7.]
 [-8. -6. -2.  5.]]

矩阵的秩（Rank）：3
矩阵的列数：4


In [5]:
#判断是否为单射，秩等于列数，则列向量线性无关，齐次方程只有0解，为单射
if rank45 == n_cols45:   
    print("\n结论：秩 = 列数，列向量线性无关。")
    print("齐次方程 Ax = 0 只有零解。")
    print("✅ 因此，T 是单射。")
else:
    print("\n结论：秩 < 列数，列向量线性相关。")
    print("齐次方程 Ax = 0 有非零解（存在自由变量）。")
    print("❌ 因此，T 不是单射。")

if rank46 == n_cols46:   
    print("\n结论：秩 = 列数，列向量线性无关。")
    print("齐次方程 Ax = 0 只有零解。")
    print("✅ 因此，T 是单射。")
else:
    print("\n结论：秩 < 列数，列向量线性相关。")
    print("齐次方程 Ax = 0 有非零解（存在自由变量）。")
    print("❌ 因此，T 不是单射。")


结论：秩 < 列数，列向量线性相关。
齐次方程 Ax = 0 有非零解（存在自由变量）。
❌ 因此，T 不是单射。

结论：秩 < 列数，列向量线性相关。
齐次方程 Ax = 0 有非零解（存在自由变量）。
❌ 因此，T 不是单射。
