In [1]:
#判断矩阵是否满射：进行行化简，是否每行都有主元，即是否行满秩，无全零行。
import numpy as np

In [2]:
A47 = np.array([
    [ 4, -7,  3,  7,  5],
    [ 6, -8,  5, 12, -8],
    [-7, 10, -8, -9, 14],
    [ 3, -5,  4,  2, -6],
    [-5,  6, -6, -7,  3]
],dtype=float)

A48 = np.array([
    [ 9, 13,  5,  6, -1],
    [14, 15, -7, -6,  4],
    [-8, -9, 12, -5, -9],
    [-5, -6, -8,  9,  8],
    [13, 14, 15,  2, 11]
],dtype=float)

In [3]:
#计算矩阵的秩和行数
rank47 = np.linalg.matrix_rank(A47)
n_rows47 = A47.shape[0]

rank48 = np.linalg.matrix_rank(A48)
n_rows48 = A48.shape[0]

In [4]:
print("矩阵 A47：")
print(A47)
print(f"\n矩阵的秩（Rank）：{rank47}")
print(f"矩阵的行数：{n_rows47}")

print("\n矩阵 A48：")
print(A48)
print(f"\n矩阵的秩（Rank）：{rank48}")
print(f"矩阵的行数：{n_rows48}")

矩阵 A47：
[[ 4. -7.  3.  7.  5.]
 [ 6. -8.  5. 12. -8.]
 [-7. 10. -8. -9. 14.]
 [ 3. -5.  4.  2. -6.]
 [-5.  6. -6. -7.  3.]]

矩阵的秩（Rank）：4
矩阵的行数：5

矩阵 A48：
[[ 9. 13.  5.  6. -1.]
 [14. 15. -7. -6.  4.]
 [-8. -9. 12. -5. -9.]
 [-5. -6. -8.  9.  8.]
 [13. 14. 15.  2. 11.]]

矩阵的秩（Rank）：4
矩阵的行数：5


In [5]:
# 判断是否为满射,A是否每一行都有主元，如果秩等于行数，则每一行都有主元，则为满射
if rank47 == n_rows47:
    print("\n结论：秩 = 行数，每一行都有主元位置。")
    print("矩阵的列向量张成整个 R^5。")
    print("✅ 因此，T 将 R^5 映上 R^5（T 是满射）。")
else:
    print("\n结论：秩 < 行数，行化简后会出现全零行。")
    print("矩阵的列向量无法张成整个 R^5。")
    print("❌ 因此，T 不能将 R^5 映上 R^5（T 不是满射）。")

# 4. 判断是否为满射
if rank48 == n_rows48:
    print("\n结论：秩 = 行数，每一行都有主元位置。")
    print("矩阵的列向量张成整个 R^5。")
    print("✅ 因此，T 将 R^5 映上 R^5（T 是满射）。")
else:
    print("\n结论：秩 < 行数，行化简后会出现全零行。")
    print("矩阵的列向量无法张成整个 R^5。")
    print("❌ 因此，T 不能将 R^5 映上 R^5（T 不是满射）。")


结论：秩 < 行数，行化简后会出现全零行。
矩阵的列向量无法张成整个 R^5。
❌ 因此，T 不能将 R^5 映上 R^5（T 不是满射）。

结论：秩 < 行数，行化简后会出现全零行。
矩阵的列向量无法张成整个 R^5。
❌ 因此，T 不能将 R^5 映上 R^5（T 不是满射）。
